stages:
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.task:
  stage: test
  image: nixos/nix
  tags: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - echo "experimental-features = nix-command flakes" >>/etc/nix/nix.conf

check:og:
  extends:
    - .task
  script:
    - nix develop -c task generate:og
    - git diff --exit-code

pages:
  stage: deploy
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  script:
    - hugo
    - hugo --config hugo-slides.toml
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

