default: true

MD007:
  indent: 2

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 119
  # Include code blocks
  code_blocks: false
  # Ignore table length violations
  tables: false
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

MD024:
  # Allow heading duplication if under different parent headings
  siblings_only: true
