baseURL = "https://haseebmajid.dev/slides"
title = "Haseeb Majid"
theme = ["github.com/joshed-io/reveal-hugo"]
contentDir = "content/slides"
publishDir = "public/slides"
staticDir = "static/slides"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
