version: "3"

tasks:
  start_server:
    watch: true
    sources:
      - 'content/**/*.md'
    cmds:
      - hugo server -D --buildFuture

  new_post:
    cmds:
      - new_post "{{.CLI_ARGS}}"

  new_talk:
    cmds:
      - hugo new --kind talk-bundle talks/{{.TALK_NAME}}
    env:
      TALK_NAME: foo

  generate:og:
    cmds:
      - ls content/posts/ | parallel 'mkdir -p content/posts/{}/images && tcardgen -c scripts/og/config.yaml --template=scripts/og/template.png -f scripts/og/fonts/ content/posts/{}/index.md -o content/posts/{}/images/cover.png'
