#!/usr/bin/env bash

TITLE=${1:-}

TITLE_SLUG="$(echo -n "$TITLE" | sed -e 's/[^[:alnum:]]/-/g' | tr -s '-' | tr A-Z a-z | tail -c +2 | head -c -1)"
DATE="$(date +"%F")"
SLUG="$DATE-$TITLE_SLUG"

git checkout -b "$SLUG"
hugo new --kind post-bundle posts/$SLUG

echo "Creating OG for content/posts/${SLUG}"
python scripts/og/generate.py content/posts/$SLUG
rm content/posts/$SLUG/images/.gitkeep
